### ISSUE TITLE
value of variable not read in server.cpp

### ISSUE THREAD

**Issue by ellezeeman** [dianestephens/fileserver_cpp#10]
Project: Client/Server
Report By: [Elle Zeeman] [Team Green]

Vulnerability Type: Others - Warning-stored value never read

Analysis Method Used: [Clang Static Analysis / Scan-build]

Vulnerability Description:
[Build Configuration] -v1.0
[Code Location] - server.cpp:650:19:
[Reasoning] -  warning: Although the value stored to 'n' is used in the enclosing expression, the value is never actually read from 'n'
[Possible Risk] - This warning will not necessarily cause a risk or error, only a reminder that a particular value is not assigned statically and the value is only updated in other parts of the program.

**Comment by dianestephens** [comment]
Issue is resolved. Thank you.
