### ISSUE TITLE
Uninitialized Variable in Server.cpp (#2)

### ISSUE THREAD

**Issue by ellezeeman** [dianestephens/fileserver_cpp#3]
Project: Client/Server
Report By: [Elle Zeeman] [Team Green]

Vulnerability Type: Others - Uninitialized Variable

Analysis Method Used: [CppCheck]

Vulnerability Description:
[Build Configuration] -v1.0
[Code Location] - fileserver_cpp-1.0/server.cpp:177:20:
[Reasoning] - error: Uninitialized variable: active_users [uninitvar]
[Possible Risk] - Program may behave in unexpected ways on a different system or when changes are made to the code. Additionally, attackers can launch a denial of service attack and crash the program. Attackers could possibly also control the value of uninitialized  variables and manipulate the program.

**Comment by dianestephens** [comment]
Issue is resolved. Thank you.
