### ISSUE TITLE
Read operation on a file that was opened only for writing

### ISSUE THREAD

**Issue by shawnwork** [dianestephens/fileserver_cpp#32]
Project:fileserver
Report By:Team Blue
Vulnerability Type:  Read operation on a file that was opened only for writing
Analysis Method Used: CppCheck
Vulnerability Description:
server.cpp:636:20: error: Read operation on a file that was opened only for writing. [readWriteOnlyFile]
          result = fread (buffer, 1, lSize, pFile);
                   ^

**Comment by dianestephens** [comment]
Issue resolved. Thank you.
