### ISSUE TITLE
Overflow Detected in server.cpp

### ISSUE THREAD

**Issue by ellezeeman** [dianestephens/fileserver_cpp#37]
The following was discovered by SVF and Clang

Here is the input that causes the vulnerability
<img width="905" alt="Screen Shot 2021-03-31 at 10 39 08 PM" src="https://user-images.githubusercontent.com/54867536/113236053-246d4500-9272-11eb-91a0-2fc3a8a34d84.png">

This is what I discovered using "clang -c -emit-llvm -g server.cpp" 
As seen by the log, several warnings regarding the pointer are raised, but the highlighted part is the most crucial. The use of memset creates an overflow.
![image](https://user-images.githubusercontent.com/54867536/113236235-7f9f3780-9272-11eb-8ca7-80ffbcbce784.png)

According to some online documentation, memset is seen as a dangerous thing to use in C/CPP code. Since the argument size is larger than the destination buffer size, not all parts of the argument will be properly passed. Instead, the program will only pass what is allowed by the destination buffer size. 

A safer alternative could be to look into the use of memcpy() within a loop - this is one alternative I found. I am not very experienced with this kind of thing so I am unsure if that would be an appropriate alternative.

**Comment by irfanOzn** [comment]
Hi Ellezeeman ,

Thank You for the report, but this bug is reported before, and fixed in commit number "9834c81aaef12c52440df96f3a4a977f4f4ccf88"

![image](https://user-images.githubusercontent.com/76975914/113237841-97c48600-9275-11eb-959d-fb039906ad5b.png)

**Comment by dianestephens** [comment]
This issue has been resolved.  Thank you.
