### ISSUE TITLE
Read operation on a file that was opened only for writing in Server.cpp

### ISSUE THREAD

**Issue by ellezeeman** [dianestephens/fileserver_cpp#4]
Project: Client/Server
Report By: [Elle Zeeman] [Team Green]

Vulnerability Type: Others - Read operation on a file that was opened only for writing

Analysis Method Used: [CppCheck]

Vulnerability Description:
[Build Configuration] -v1.0
[Code Location] - fileserver_cpp-1.0/server.cpp:636:20:
[Reasoning] - error:  Read operation on a file that was opened only for writing. [readWriteOnlyFile]
[Possible Risk] - Accidentally writing to a file that was meant to be opened for reading only, which could cause complications to the system; run in unexpected ways.

**Comment by dianestephens** [comment]
Issue is resolved. Thank you.
