### ISSUE TITLE
Value stored to 'created' is never read server.cpp

### ISSUE THREAD

**Issue by ellezeeman** [dianestephens/fileserver_cpp#6]
Project: Client/Server
Report By: [Elle Zeeman] [Team Green]

Vulnerability Type: Others - Warning-stored value never read

Analysis Method Used: [Clang Static Analysis / Scan-build]

Vulnerability Description:
[Build Configuration] -v1.0
[Code Location] - server.cpp:338:17: , server.cpp:346:13: 
[Reasoning] -  warning: Value stored to 'created' is never read
[Possible Risk] - This warning will not necessarily cause a risk or error, only a reminder that a particular value is not assigned statically and the value is only updated in other parts of the program.

**Comment by dianestephens** [comment]
Issue is resolved. Thank you.
